### PR TITLE
feat: added sql translation

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by TheFantomas** [comment]
Why add en?

**Comment by MoskalykA** [comment]
> Why add en?

It's conventional like all the other rests

**Comment by Gellipapa** [comment]
@MoskalykA Hi! Thank you for added new sql translate but please remove EN version because EN is default and you can found in root folder.

**Comment by MoskalykA** [comment]
> @MoskalykA Hi! Thank you for added new sql translate but please remove EN version because EN is default and you can found in root folder.

hey, it's good

**Comment by Gellipapa** [comment]
@MoskalykA Hi! It's correct, thank you fast response.

**Pull request merged**
